# Generated by Django 4.1.4 on 2023-01-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxe', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
