# Generated by Django 4.1.4 on 2023-01-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luxe', '0003_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='imgs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxe.product')),
            ],
        ),
    ]
